project:
  type: website

website:
  title: "Sentiment analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Leo Tolstoy
        menu:
          - href: anna-karenina.qmd
            text: Anna Karenina
          - href: war-peace.qmd
            text: War and Peace
      - text: Louisa May Alcott
        menu:
          - href: little-women.qmd
            text: Little Women
      - text: Agatha Christie
        menu:
          - href: murder.qmd
            text: Murder on the Orient Express
      - text: Charles Dickens
        menu:
          - href: oliver-twist.qmd
            text: Oliver Twist
      - text: Daniel Defoe
        menu:
          - href: robin.qmd
            text: Robinson Crusoe
      - text: Alexander Pushkin
        menu:
          - href: captain-daughter.qmd
            text: The Captain's Daughter
      - text: Mark Twain
        menu:
          - href: tom-sawyer.qmd
            text: The Adventures of Tom Sawyer
      - text: Jack London
        menu:
          - href: white-fang.qmd
            text: White Fang
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



