---
title: "The Captain's Daughter"
execute:
    echo: false
    message: false
---

```{r}
#| message: false
library(tidytext)
library(dplyr)
library(stringr)
library(readr)
library(tidyr)
```
```{r}
#| message: false
dirt_captain_daughter <-  "~/Desktop/finalfinal/data/captain-daughter.txt"
```

```{r}
#| message: false
afinn <- get_sentiments("afinn")

positive <- get_sentiments("afinn") |> filter(value > 0)

negative <- get_sentiments("afinn") |> filter(value < 0)

lines_captain_daughter <- read_lines(dirt_captain_daughter) 
dir_captain_daughter <- tibble(text = lines_captain_daughter)
```

```{r}
#| message: false
tidy_book_captain_daughter <- dir_captain_daughter %>%
  mutate(
    linenumber = row_number(),
    chapter = cumsum(str_detect(text, regex("^chapter [ivxlc]+", ignore_case = TRUE)))
  ) %>%
  unnest_tokens(word, text) %>%
  filter(chapter > 0)

tidy_book_captain_daughter <- tidy_book_captain_daughter %>%
  left_join(get_sentiments("afinn"), by = "word")
```

```{r}
#| message: false
sentiments_pos_captain_daughter <- tidy_book_captain_daughter %>%
  inner_join(positive) %>%
  count(word, sort = TRUE)

sentiments_neg_captain_daughter <- tidy_book_captain_daughter %>%
  inner_join(negative) %>%
  count(word, sort = TRUE)

word_scores_captain_daughter <- tidy_book_captain_daughter %>%
  count(word, sort = TRUE)

word_sentiment_data_captain_daughter <- word_scores_captain_daughter %>%
  left_join(get_sentiments("afinn"), by = "word") %>%
  mutate(word_avg_sent = n * value) %>%
  drop_na()
                                                     
```


```{r}
#| message: false
library(ggplot2)

word_sentiment_data_captain_daughter |> 
  ggplot(aes(word, word_avg_sent, color="red")) + 
  geom_col() + 
  scale_x_discrete(labels = NULL) + 
  labs(title="Average sentimental scored for each word in the book", 
       x="Words", 
       y="Average Sentimental score per word") + 
  theme(legend.position = "none")
```

```{r}
#| message: false
chapter_info_captain_daughter <- tidy_book_captain_daughter %>%
  select(chapter, linenumber, word) %>% 
  distinct()

chapter_sentiment_captain_daughter <- tidy_book_captain_daughter %>%
  group_by(chapter) %>%
  summarise(median_sentiment = median(value, na.rm = TRUE))

tidy_book_sentiment_captain_daughter <- tidy_book_captain_daughter %>%
  select(-value) %>%  
  left_join(get_sentiments("afinn"), by = "word") %>%
  drop_na(value)

chapter_sentiment_captain_daughter <- tidy_book_sentiment_captain_daughter %>%
  group_by(chapter) %>%
    summarise(median_sentiment = median(value, na.rm = TRUE))
```

```{r}
#| message: false
library(plotly)

p <- chapter_sentiment_captain_daughter %>%
  ggplot(aes(x = chapter, y = median_sentiment)) +
  geom_point(color = "red", size = 3) +
  geom_line(color = "red") +
  labs(title = "Average sentimental score in each chapter",
       x = "Chapter",
       y = "Median Sentiment") + 
  theme(legend.position = "none")

ggplotly(p)
```

```{r}
#| message: false
library(dplyr)
library(tidytext)
library(reshape2)
library(wordcloud)

tidy_book_captain_daughter %>%
  inner_join(get_sentiments("bing"), by = "word") %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("#bd3e2f", "#769e6d"), max.words = 250)
```

```{r}
captain_daughter_summary <- tibble(
  book = "The Captain's Daughter",
  author = "Alexander Pushkin",
  country = "Russia",
  median_sentiment = median(chapter_sentiment_captain_daughter$median_sentiment, na.rm = TRUE)
)

write_rds(captain_daughter_summary, "data/captain_daughter_summary.rds")
```

```{r}
chapter_sentiment_captain_daughter <- chapter_sentiment_captain_daughter %>%
  mutate(book = "The Captain's Daughter")

saveRDS(chapter_sentiment_captain_daughter, "data/chapter_sentiment_captain_daughter.rds")
```

