---
title: "little-women"
execute:
    echo: false
    message: false
---

```{r}
#| message: false
library(tidytext)
library(dplyr)
library(stringr)
library(readr)
library(tidyr)
```
```{r}
#| message: false
dirt_little_women <-  "~/Desktop/finalfinal/data/little-women.txt"
```

```{r}
#| message: false
afinn <- get_sentiments("afinn")

positive <- afinn |> filter(value > 0)

negative <- afinn |> filter(value < 0)

lines_little_women <- read_lines(dirt_little_women)
dir_little_women <- tibble(text = lines_little_women)
```

```{r}
#| message: false
afinn <- get_sentiments("afinn")

positive <- afinn |> filter(value > 0)

negative <- afinn |> filter(value < 0)

lines_little_women <- read_lines(dirt_little_women)
dir_little_women <- tibble(text = lines_little_women)
```

```{r}
#| message: false
tidy_book_little_women <- dir_little_women %>%
  mutate(
    linenumber = row_number(),
    chapter = cumsum(str_detect(text, regex("^part\\s+\\d+\\b.*$", ignore_case = TRUE)))
  ) %>%
  unnest_tokens(word, text) %>%
  filter(chapter > 0) 

tidy_book_little_women <- tidy_book_little_women %>%
  left_join(get_sentiments("afinn"), by = "word")
```


```{r}
#| message: false
sentiments_pos_little_women <- tidy_book_little_women %>%
  inner_join(positive) %>%
  count(word, sort = TRUE)

sentiments_neg_little_women <- tidy_book_little_women %>%
  inner_join(negative) %>%
  count(word, sort = TRUE)

word_scores_little_women <- tidy_book_little_women %>%
  count(word, sort = TRUE)

word_sentiment_data_little_women <- word_scores_little_women %>%
  left_join(afinn, by = "word") %>%
  mutate(word_avg_sent = n * value) %>%
  drop_na()
```


```{r}
#| message: false
library(ggplot2)

word_sentiment_data_little_women |> 
  ggplot(aes(word, word_avg_sent)) + 
  geom_col() + 
  scale_x_discrete(labels = NULL)
```

```{r}
#| message: false
tidy_book_sentiment_little <- tidy_book_little_women %>%
  select(-value) %>%
  left_join(get_sentiments("afinn"), by = "word") %>%
  drop_na(value)

chapter_sentiment_little <- tidy_book_sentiment_little %>%
  group_by(chapter) %>%
  summarise(median_sentiment = median(value, na.rm = TRUE))
```

```{r}
#| message: false
library(ggplot2)
library(plotly)

p <- chapter_sentiment_little %>%
  ggplot(aes(x = chapter, y = median_sentiment)) +
  geom_point(color = "darkgreen", size = 3) +
  geom_line(color = "darkgreen") +
  labs(title = "Median Sentiment by Chapter – Little Women",
       x = "Chapter",
       y = "Median Sentiment (AFINN)") +
  theme_minimal() + labs(title="Most used words by their sentimental values")

ggplotly(p)
```

